### ISSUE TITLE
How to use it on Windows?

### ISSUE THREAD

**Issue by frederikhors** [kennytm/tzfile#9]
Windows user here, is there a chance to use it?

**Comment by kennytm** [comment]
You can't use `Tz::named()` and `Tz::local()` on Windows. But if you already have [a copy of the tz database](https://www.iana.org/time-zones) somewhere, you can read the file into memory and then [use `Tz::parse()`](https://docs.rs/tzfile/latest/tzfile/struct.Tz.html#method.parse).
